version: "3"
services:
  transactions-app:
    build: .
    user: node
    container_name: transactions_api
    tty: true
    stdin_open: true
    command: npm run dev
    image: transactions-api:8.3
    restart: always
    working_dir: /app
    volumes:
      - ./src/:/app/src
      - ./tests/:/app/tests
    depends_on:
      - db
    ports:
      - 3001:3001
    environment:
      DB_USER: root
      DB_PASSWORD: password
      DB_HOST: db
      DB_NAME: transactions_api
      DB_PORT: 3306
      JWT_SECRET: secret
  db:
    container_name: transactions_db
    image: mysql:8.0.32
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
