version: "3"
services:
  node:
    build: .
    container_name: jwt_token
    tty: true
    stdin_open: true
    command: bash
    restart: always
    working_dir: /app
    volumes:
      - ./src/:/app/src
      - ./__tests__/:/app/__tests__/
    depends_on:
      - db
    ports:
      - 3001:3001
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: db # Nome do service logo abaixo
      JWT_SECRET: secretJWT
      API_HOST: 'node'
      API_PORT: 3001
      NODE_ENV: 'development'
    networks:
      - jwt_token_net
  db:
    container_name: jwt_token_db
    image: mysql:8.0.23
    platform: linux/x86_64
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - jwt_token_net

networks:
  jwt_token_net:
    driver: bridge