version: '3.1'

services:
  mysql:
    image: mysql:8.0.32
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306

  api:
    build: ./
    restart: always
    container_name: api
    ports:
      - 3001:3001
    environment:
      - DB_HOST=mysql
      - DB_NAME=hospital_control
      - DB_USER=root
      - DB_PASSWORD=password
      - API_PORT=3001
    volumes:
      - ./:/usr/app
    user: node
    working_dir: /usr/app
    tty: true
    stdin_open: true
    depends_on:
      - mysql
